---
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      # - id: check-hooks-apply  # Leave nbqa in here.
      # - id: identity  # Prints all files passed to pre-commits. Debugging.
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.13.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=50000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
        types: [text]
      - id: forbid-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
      - id: check-ast
      - id: check-docstring-first
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args:
          - --fix
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - metadata.kernelspec metadata.language_info.version metadata.vscode
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies: [mdformat-myst, mdformat-ruff]
        args: [--wrap, '88']
        exclude: slides.md|instructions.md
ci:
  autoupdate_schedule: monthly
