---
name: COURSE_SLUG
channels: [conda-forge, nodefaults]
dependencies:
  - conda-lock
  - ipykernel
  - ipywidgets
  - jupyterlab
  - nodejs
  - openpyxl==3.1.0
  - pandas
  - pdbpp
  - pip
  - plotly
  - pre-commit
  - pydata-sphinx-theme>=0.13.3
  - pytask-parallel
  - pytask>=0.3
  - pytest
  - pytest-cov
  - pytest-xdist
  - python==3.11
  - pyyaml
  - setuptools_scm
  - sphinx
  - sphinx-automodapi
  - sphinx-copybutton
  - statsmodels
  - toml
  - pip: [-e ., kaleido, jupyter-book]
