---
name: epp
channels: [conda-forge, nodefaults]
dependencies:
  - conda-lock
  - gitpython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - nodejs
  - numba
  - openpyxl
  - pandas
  - pdbpp
  - pip
  - plotly
  - pre-commit
  - pygraphviz
  - pydata-sphinx-theme>=0.13.3
  - pytask
  - pytask-parallel
  - pytest
  - pytest-cov
  - pytest-xdist
  - python==3.11
  - pyyaml
  - scikit-learn
  - snakeviz
  - setuptools_scm
  - sphinx
  - sphinx-automodapi
  - sphinx-copybutton
  - statsmodels
  - toml
  - xlrd>=1.0
  - pip: [-e ., kaleido, jupyter-book]
