---
name: epp_topics
channels: [conda-forge, nodefaults, conda-forge/label/pytask_rc]
dependencies:
  - conda-lock
  - deepdiff
  - gitpython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - nodejs
  - numba
  - openpyxl
  - pandas >= 2.1
  - pyarrow >= 13.0
  - pdbpp
  - pip
  - plotly
  - pre-commit
  - pygraphviz
  - pydata-sphinx-theme>=0.13.3
  - pytask >= 0.4.0rc2
  # - pytask-parallel  # Do not use, slidev exports get mixed up.
  - pytest
  - pytest-cov
  - pytest-xdist
  - python==3.11
  - pyyaml
  - scikit-learn
  - snakeviz
  - setuptools_scm
  - sphinx
  - sphinx-automodapi
  - sphinx-copybutton
  - sphinxcontrib-mermaid
  - statsmodels
  - toml
  - xlrd>=1.0
  - pybaum
  - pip: [-e ., kaleido, jupyter-book, pyperclip]
