---
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: COURSE_TITLE
author: TEACHER_NAMES
logo: uni-bonn-blue.jpg

# Short description about the book
description: >-
  COURSE_DESCRIPTION, COURSE_DATE
# HTML-specific settings
html:
  home_page_in_navbar: false
  # Add GitHub buttons to your book
  # See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
  use_issues_button: false
  use_repository_button: false
  extra_footer: |
    <p>
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
    <img alt="Creative Commons License" style="border-width:0"
    src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" />
    </a><br />This work is licensed under a
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
    Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
    </p>
# Interact link settings
notebook_interface: notebook
# Information about where the book exists on the web
repository:
  url: https://github.com/iame-uni-bonn/course_jb_template.git
  path_to_book: student_book
# LaTeX settings
bibtex_bibfiles: [references.bib]
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex
sphinx:
  config:
    # Render plotly figures
    suppress_warnings: [mystnb.unknown_mime_type]
    html_show_copyright: false
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: author_year
    exclude_patterns: ['**/slides.md']
    html_theme_options:
      repository_url: https://github.com/iame-uni-bonn/course_jb_template.git
      # launch_buttons:
      #   jupyterhub_url: https://jupyterhub.hrz.uni-bonn.de
  extra_extensions: [sphinx.ext.todo]
